version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/my-app:${IMAGE_TAG:-latest}
    container_name: my-app-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

